///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AppUserDataUserModel {
/*
{
  "sub": "d2776f6b-5d84-4b4c-9da7-89a5d3481f60",
  "email": "jinsa@mailinator.com",
  "name": "jinsa",
  "mobileNumber": "1234567890",
  "profileImage": "http://168.231.74.154:4004/files/users/d2776f6b-5d84-4b4c-9da7-89a5d3481f60/profile_1767077399024.jpg",
  "isSubscription": false,
  "issuedAt": "2026-01-07T13:19:03.000Z",
  "expiresAt": "2026-01-08T13:19:03.000Z",
  "isEmailVerified": true,
  "isVibrationEnabled": false,
  "isSoundEnabled": true,
  "notificationSound": "Gentle Chime",
  "isGentleChime": true
} 
*/

  String? sub;
  String? email;
  String? name;
  String? mobileNumber;
  String? profileImage;
  bool? isSubscription;
  String? issuedAt;
  String? expiresAt;
  bool? isEmailVerified;
  bool? isVibrationEnabled;
  bool? isSoundEnabled;
  String? notificationSound;
  bool? isGentleChime;
  bool? isEmergencyCard;
  bool? isSnooze;

  AppUserDataUserModel({
    this.sub,
    this.email,
    this.name,
    this.mobileNumber,
    this.profileImage,
    this.isSubscription,
    this.issuedAt,
    this.expiresAt,
    this.isEmailVerified,
    this.isVibrationEnabled,
    this.isSoundEnabled,
    this.notificationSound,
    this.isGentleChime,
    this.isEmergencyCard,
    this.isSnooze,
  });
  AppUserDataUserModel.fromJson(Map<String, dynamic> json) {
    sub = json['sub']?.toString();
    email = json['email']?.toString();
    name = json['name']?.toString();
    mobileNumber = json['mobileNumber']?.toString();
    profileImage = json['profileImage']?.toString();
    isSubscription = json['isSubscription'];
    issuedAt = json['issuedAt']?.toString();
    expiresAt = json['expiresAt']?.toString();
    isEmailVerified = json['isEmailVerified'];
    isVibrationEnabled = json['isVibrationEnabled'];
    isSoundEnabled = json['isSoundEnabled'];
    notificationSound = json['notificationSound']?.toString();
    isGentleChime = json['isGentleChime'];
    isSnooze = json['isSnooze'];
    isEmergencyCard = json['isEmergencyCard'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['sub'] = sub;
    data['email'] = email;
    data['name'] = name;
    data['mobileNumber'] = mobileNumber;
    data['profileImage'] = profileImage;
    data['isSubscription'] = isSubscription;
    data['issuedAt'] = issuedAt;
    data['expiresAt'] = expiresAt;
    data['isEmailVerified'] = isEmailVerified;
    data['isVibrationEnabled'] = isVibrationEnabled;
    data['isSoundEnabled'] = isSoundEnabled;
    data['notificationSound'] = notificationSound;
    data['isGentleChime'] = isGentleChime;
    data['isEmergencyCard'] = isEmergencyCard;
    data['isSnooze'] = isSnooze;
    return data;
  }
}

class AppUserData {
/*
{
  "access_token": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMjc3NmY2Yi01ZDg0LTRiNGMtOWRhNy04OWE1ZDM0ODFmNjAiLCJlbWFpbCI6ImppbnNhQG1haWxpbmF0b3IuY29tIiwiaXNTdWJzY3JpcHRpb24iOmZhbHNlLCJpc0VtYWlsVmVyaWZpZWQiOnRydWUsImlhdCI6MTc2Nzc5MTk0MywiZXhwIjoxNzY3ODc4MzQzfQ.j3Y7dGdys10lsmfw8ZcG7wPrGncgzyF9pOf56ujd8IlFX6I7LW-D1uPEpLMr3p3K9JG8gPAGUCGk-ZOkKMRttw",
  "user_model": {
    "sub": "d2776f6b-5d84-4b4c-9da7-89a5d3481f60",
    "email": "jinsa@mailinator.com",
    "name": "jinsa",
    "mobileNumber": "1234567890",
    "profileImage": "http://168.231.74.154:4004/files/users/d2776f6b-5d84-4b4c-9da7-89a5d3481f60/profile_1767077399024.jpg",
    "isSubscription": false,
    "issuedAt": "2026-01-07T13:19:03.000Z",
    "expiresAt": "2026-01-08T13:19:03.000Z",
    "isEmailVerified": true,
    "isVibrationEnabled": false,
    "isSoundEnabled": true,
    "notificationSound": "Gentle Chime",
    "isGentleChime": true
  }
} 
*/

  String? accessToken;
  AppUserDataUserModel? userModel;

  AppUserData({
    this.accessToken,
    this.userModel,
  });
  AppUserData.fromJson(Map<String, dynamic> json) {
    accessToken = json['access_token']?.toString();
    userModel = (json['user_model'] != null)
        ? AppUserDataUserModel.fromJson(json['user_model'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['access_token'] = accessToken;
    if (userModel != null) {
      data['user_model'] = userModel!.toJson();
    }
    return data;
  }
}

class AppUser {
/*
{
  "isSuccess": true,
  "statusCode": 200,
  "message": "Login successful",
  "data": {
    "access_token": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMjc3NmY2Yi01ZDg0LTRiNGMtOWRhNy04OWE1ZDM0ODFmNjAiLCJlbWFpbCI6ImppbnNhQG1haWxpbmF0b3IuY29tIiwiaXNTdWJzY3JpcHRpb24iOmZhbHNlLCJpc0VtYWlsVmVyaWZpZWQiOnRydWUsImlhdCI6MTc2Nzc5MTk0MywiZXhwIjoxNzY3ODc4MzQzfQ.j3Y7dGdys10lsmfw8ZcG7wPrGncgzyF9pOf56ujd8IlFX6I7LW-D1uPEpLMr3p3K9JG8gPAGUCGk-ZOkKMRttw",
    "user_model": {
      "sub": "d2776f6b-5d84-4b4c-9da7-89a5d3481f60",
      "email": "jinsa@mailinator.com",
      "name": "jinsa",
      "mobileNumber": "1234567890",
      "profileImage": "http://168.231.74.154:4004/files/users/d2776f6b-5d84-4b4c-9da7-89a5d3481f60/profile_1767077399024.jpg",
      "isSubscription": false,
      "issuedAt": "2026-01-07T13:19:03.000Z",
      "expiresAt": "2026-01-08T13:19:03.000Z",
      "isEmailVerified": true,
      "isVibrationEnabled": false,
      "isSoundEnabled": true,
      "notificationSound": "Gentle Chime",
      "isGentleChime": true
    }
  }
} 
*/

  bool? isSuccess;
  int? statusCode;
  String? message;
  AppUserData? data;

  AppUser({
    this.isSuccess,
    this.statusCode,
    this.message,
    this.data,
  });
  AppUser.fromJson(Map<String, dynamic> json) {
    isSuccess = json['isSuccess'];
    statusCode = json['statusCode']?.toInt();
    message = json['message']?.toString();
    data = (json['data'] != null) ? AppUserData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['isSuccess'] = isSuccess;
    data['statusCode'] = statusCode;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
