///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AppUserDataUserModel {
/*
{
  "sub": "de242628-9039-4561-b86b-5f2674fe14be",
  "email": "oppo@mailinator.com",
  "roleId": 1,
  "fullName": "linsa",
  "mobileNumber": "",
  "profileImage": "",
  "gender": "",
  "isEmailVerified": true,
  "latitude": "null",
  "longitude": "null",
  "isLiveTrackingActive": false,
  "lastLocationUpdate": "null",
  "referralCode": "P4AZ42DM",
  "hourlyRate": "null",
  "address": "",
  "isSubscription": false,
  "issuedAt": "2026-03-19T10:16:08.000Z",
  "expiresAt": "2026-03-26T10:16:08.000Z"
} 
*/

  String? sub;
  String? email;
  int? roleId;
  String? fullName;
  String? mobileNumber;
  String? profileImage;
  String? gender;
  bool? isEmailVerified;
  String? latitude;
  String? longitude;
  bool? isLiveTrackingActive;
  String? lastLocationUpdate;
  String? referralCode;
  String? hourlyRate;
  String? address;
  bool? isSubscription;
  String? issuedAt;
  String? expiresAt;

  AppUserDataUserModel({
    this.sub,
    this.email,
    this.roleId,
    this.fullName,
    this.mobileNumber,
    this.profileImage,
    this.gender,
    this.isEmailVerified,
    this.latitude,
    this.longitude,
    this.isLiveTrackingActive,
    this.lastLocationUpdate,
    this.referralCode,
    this.hourlyRate,
    this.address,
    this.isSubscription,
    this.issuedAt,
    this.expiresAt,
  });
  AppUserDataUserModel.fromJson(Map<String, dynamic> json) {
    sub = json['sub']?.toString();
    email = json['email']?.toString();
    roleId = json['roleId']?.toInt();
    fullName = json['fullName']?.toString();
    mobileNumber = json['mobileNumber']?.toString();
    profileImage = json['profileImage']?.toString();
    gender = json['gender']?.toString();
    isEmailVerified = json['isEmailVerified'];
    latitude = json['latitude']?.toString();
    longitude = json['longitude']?.toString();
    isLiveTrackingActive = json['isLiveTrackingActive'];
    lastLocationUpdate = json['lastLocationUpdate']?.toString();
    referralCode = json['referralCode']?.toString();
    hourlyRate = json['hourlyRate']?.toString();
    address = json['address']?.toString();
    isSubscription = json['isSubscription'];
    issuedAt = json['issuedAt']?.toString();
    expiresAt = json['expiresAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['sub'] = sub;
    data['email'] = email;
    data['roleId'] = roleId;
    data['fullName'] = fullName;
    data['mobileNumber'] = mobileNumber;
    data['profileImage'] = profileImage;
    data['gender'] = gender;
    data['isEmailVerified'] = isEmailVerified;
    data['latitude'] = latitude;
    data['longitude'] = longitude;
    data['isLiveTrackingActive'] = isLiveTrackingActive;
    data['lastLocationUpdate'] = lastLocationUpdate;
    data['referralCode'] = referralCode;
    data['hourlyRate'] = hourlyRate;
    data['address'] = address;
    data['isSubscription'] = isSubscription;
    data['issuedAt'] = issuedAt;
    data['expiresAt'] = expiresAt;
    return data;
  }
}

class AppUserData {
/*
{
  "access_token": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZTI0MjYyOC05MDM5LTQ1NjEtYjg2Yi01ZjI2NzRmZTE0YmUiLCJlbWFpbCI6Im9wcG9AbWFpbGluYXRvci5jb20iLCJyb2xlSWQiOjEsImZ1bGxOYW1lIjoibGluc2EiLCJtb2JpbGVOdW1iZXIiOiIiLCJwcm9maWxlSW1hZ2UiOiIiLCJnZW5kZXIiOiIiLCJpc0VtYWlsVmVyaWZpZWQiOnRydWUsImxhdGl0dWRlIjpudWxsLCJsb25naXR1ZGUiOm51bGwsImlzTGl2ZVRyYWNraW5nQWN0aXZlIjpmYWxzZSwibGFzdExvY2F0aW9uVXBkYXRlIjpudWxsLCJyZWZlcnJhbENvZGUiOiJQNEFaNDJETSIsImhvdXJseVJhdGUiOm51bGwsImFkZHJlc3MiOiIiLCJpc1N1YnNjcmlwdGlvbiI6ZmFsc2UsImlhdCI6MTc3MzkxNTM2OCwiZXhwIjoxNzc0NTIwMTY4fQ.SNqU_jWZEU67U3VGsra81lk0H9BEfaBrWw6TVbEOJPPohAOFDrPp5U5XdmJUkIUsCmc5CSS7UnSTCqqkQlcyag",
  "user_model": {
    "sub": "de242628-9039-4561-b86b-5f2674fe14be",
    "email": "oppo@mailinator.com",
    "roleId": 1,
    "fullName": "linsa",
    "mobileNumber": "",
    "profileImage": "",
    "gender": "",
    "isEmailVerified": true,
    "latitude": "null",
    "longitude": "null",
    "isLiveTrackingActive": false,
    "lastLocationUpdate": "null",
    "referralCode": "P4AZ42DM",
    "hourlyRate": "null",
    "address": "",
    "isSubscription": false,
    "issuedAt": "2026-03-19T10:16:08.000Z",
    "expiresAt": "2026-03-26T10:16:08.000Z"
  }
} 
*/

  String? accessToken;
  AppUserDataUserModel? userModel;

  AppUserData({
    this.accessToken,
    this.userModel,
  });
  AppUserData.fromJson(Map<String, dynamic> json) {
    accessToken = json['access_token']?.toString();
    userModel = (json['user_model'] != null) ? AppUserDataUserModel.fromJson(json['user_model']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['access_token'] = accessToken;
    if (userModel != null) {
      data['user_model'] = userModel!.toJson();
    }
    return data;
  }
}

class AppUser {
/*
{
  "isSuccess": true,
  "statusCode": 200,
  "message": "Login successful",
  "data": {
    "access_token": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZTI0MjYyOC05MDM5LTQ1NjEtYjg2Yi01ZjI2NzRmZTE0YmUiLCJlbWFpbCI6Im9wcG9AbWFpbGluYXRvci5jb20iLCJyb2xlSWQiOjEsImZ1bGxOYW1lIjoibGluc2EiLCJtb2JpbGVOdW1iZXIiOiIiLCJwcm9maWxlSW1hZ2UiOiIiLCJnZW5kZXIiOiIiLCJpc0VtYWlsVmVyaWZpZWQiOnRydWUsImxhdGl0dWRlIjpudWxsLCJsb25naXR1ZGUiOm51bGwsImlzTGl2ZVRyYWNraW5nQWN0aXZlIjpmYWxzZSwibGFzdExvY2F0aW9uVXBkYXRlIjpudWxsLCJyZWZlcnJhbENvZGUiOiJQNEFaNDJETSIsImhvdXJseVJhdGUiOm51bGwsImFkZHJlc3MiOiIiLCJpc1N1YnNjcmlwdGlvbiI6ZmFsc2UsImlhdCI6MTc3MzkxNTM2OCwiZXhwIjoxNzc0NTIwMTY4fQ.SNqU_jWZEU67U3VGsra81lk0H9BEfaBrWw6TVbEOJPPohAOFDrPp5U5XdmJUkIUsCmc5CSS7UnSTCqqkQlcyag",
    "user_model": {
      "sub": "de242628-9039-4561-b86b-5f2674fe14be",
      "email": "oppo@mailinator.com",
      "roleId": 1,
      "fullName": "linsa",
      "mobileNumber": "",
      "profileImage": "",
      "gender": "",
      "isEmailVerified": true,
      "latitude": "null",
      "longitude": "null",
      "isLiveTrackingActive": false,
      "lastLocationUpdate": "null",
      "referralCode": "P4AZ42DM",
      "hourlyRate": "null",
      "address": "",
      "isSubscription": false,
      "issuedAt": "2026-03-19T10:16:08.000Z",
      "expiresAt": "2026-03-26T10:16:08.000Z"
    }
  }
} 
*/

  bool? isSuccess;
  int? statusCode;
  String? message;
  AppUserData? data;

  AppUser({
    this.isSuccess,
    this.statusCode,
    this.message,
    this.data,
  });
  AppUser.fromJson(Map<String, dynamic> json) {
    isSuccess = json['isSuccess'];
    statusCode = json['statusCode']?.toInt();
    message = json['message']?.toString();
    data = (json['data'] != null) ? AppUserData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['isSuccess'] = isSuccess;
    data['statusCode'] = statusCode;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
